---
# tasks file for default/php7
- name: Install php7
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - php7.2
    - php7.2-mysql
    - php7.2-curl
    - php7.2-gd
    - php7.2-fpm
    - php7.2-mbstring
    - php7.2-xml
- name: Set sendmail_path to sendmail -t -i
  become: true
  ini_file: dest=/etc/php/7.2/fpm/php.ini section=PHP option=sendmail_path value='sendmail -t -i'
  notify:
    - restart nginx
    - restart php-fpm
- name: Setting PHP error log path to /var/log/nginx/php_errors.log
  become: true
  ini_file: dest=/etc/php/7.2/fpm/php.ini section=PHP option=error_log value='/var/log/nginx/php_errors.log'
  notify:
    - restart nginx
    - restart php-fpm
- name: Ensure default www.conf is gone
  file: path=/etc/php/7.2/fpm/pool.d/www.conf state=absent
- name: Loading php-fpm configuration
  template: src=php-fpm-configuration.conf dest=/etc/php/7.2/fpm/pool.d/{{ projectname }}.conf
  notify:
    - restart nginx
    - restart php-fpm


